name: BlazePose RTSP Detector
version: "1.0"
slug: blazepose_rtsp_detector
description: A BlazePose detector for RTSP stream.
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  input_source: "rtsp://admin:password@192.168.1.100:554/onvif2"
schema:
  input_source: str
